/**
 * Copyright (c) 2013-14 Samuel A. Rebelsky.  All rights reserved.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the Lesser GNU General Public License as published 
 * by the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program.  If not, see <http://www.gnu.org/licenses/>.
 */

import edu.grinnell.glimmer.ushahidi.UshahidiCategory;
import edu.grinnell.glimmer.ushahidi.UshahidiIncident;
import edu.grinnell.glimmer.ushahidi.UshahidiUtils;
import edu.grinnell.glimmer.ushahidi.UshahidiWebReporter;

import java.time.LocalDateTime;

/**
 * A simple test of the Ushahidi Web reporter.  Takes the server from 
 * the command line, connects, and prints out all of the incidents.
 *
 * @version     0.1 of 23 August 2014
 * @author      Samuel A. Rebelsky
 */
public class WebReporterExperiment
{
  /**
   * Connect to the server given on the command line.
   */
  public static void main(String[] args)
    throws Exception
  {
    UshahidiIncident incident = 
        new UshahidiIncident(1111, "Programmatically generated incident",
            LocalDateTime.now(),
            UshahidiUtils.SAMPLE_LOCATION,
            "Generated by WebReporterExperiment",
            new UshahidiCategory[] {
              new UshahidiCategory(1),
              new UshahidiCategory(3)
            });
    UshahidiWebReporter.submit("http://ushahidi1.grinnell.edu/sandbox",
        incident);
  } // main(String[])
} // WebClientExperiment

